/*
 * app
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Inventory : The Inventory structure contains summary information of the Pet Store's inventory.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Inventory {
    /// Total number of pets sold.
    #[serde(rename = "sold")]
    pub sold: i64,
    /// Total number of new pets.
    #[serde(rename = "new")]
    pub new: i64,
    /// Total number of available pets.
    #[serde(rename = "available")]
    pub available: i64,
}

impl Inventory {
    /// The Inventory structure contains summary information of the Pet Store's inventory.
    pub fn new(sold: i64, new: i64, available: i64) -> Inventory {
        Inventory {
            sold,
            new,
            available,
        }
    }
}


