/*
 * app
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OrderRequest : An OrderRequest contains the adopter ID and the ID of the pet being purchased.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderRequest {
    /// An adopter's user id
    #[serde(rename = "adopter")]
    pub adopter: i64,
    /// A pet's pet id
    #[serde(rename = "pet")]
    pub pet: i64,
}

impl OrderRequest {
    /// An OrderRequest contains the adopter ID and the ID of the pet being purchased.
    pub fn new(adopter: i64, pet: i64) -> OrderRequest {
        OrderRequest {
            adopter,
            pet,
        }
    }
}


