/*
 * app
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Order {
    /// The order ID.
    #[serde(rename = "id")]
    pub id: String,
    /// An adopter's user id.
    #[serde(rename = "adopter")]
    pub adopter: i64,
    /// A pet's pet id.
    #[serde(rename = "pet")]
    pub pet: i64,
    /// The date the order was placed.
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "status")]
    pub status: crate::models::OrderStatus,
    /// Whether or not the order is considered complete, regardless of status.
    #[serde(rename = "complete")]
    pub complete: Option<serde_json::Value>,
}

impl Order {
    pub fn new(id: String, adopter: i64, pet: i64, date: String, status: crate::models::OrderStatus, complete: Option<serde_json::Value>) -> Order {
        Order {
            id,
            adopter,
            pet,
            date,
            status,
            complete,
        }
    }
}


