/*
 * app
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OrderStatus : The OrderStatus enum represents all statuses an order can be in.

/// The OrderStatus enum represents all statuses an order can be in.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderStatus {
    #[serde(rename = "placed")]
    Placed,
    #[serde(rename = "shipped")]
    Shipped,
    #[serde(rename = "canceled")]
    Canceled,

}

impl ToString for OrderStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Placed => String::from("placed"),
            Self::Shipped => String::from("shipped"),
            Self::Canceled => String::from("canceled"),
        }
    }
}

impl Default for OrderStatus {
    fn default() -> OrderStatus {
        Self::Placed
    }
}




